### ISSUE TITLE
Inconsistent implementation between ExampleServices and DefaultService

### ISSUE THREAD

**Issue by glauterpro** [singnet/snet-betav1-dapp#195]
**Is your feature request related to a problem? Please describe.**
I think we should drive the user to use an example with all basic service features. Including service(protobuf service) list and method list.

Following the DefaultService component, yes, I can write my new service ui component because I already know the differences.

But we have a component called ExampleService where the implementation is quite different of the DefaultService and only have a method list.

I don't know if we have a motivation for that, but I think a developer can get confused about what component is better to follow and start developing a service ui. Moreover, I think both components should be very similar.

**Describe the solution you'd like**
Improve the implementation of one of these two components and get them consistent.

**Describe alternatives you've considered**
Create a doc for that explaining differences or create a tutorial for "Creating new service UI"

**Comment by ferrouswheel** [comment]
Both the example and default service's are not great for service developers wanting to create a new service, which is why I add a TemplateService in #183 which people should use. This should be updated as we decide on any conventions to follow. It should also be well documented in the code so it's obvious what a service developer has to implement and what they can ignore.

I don't think the DefaultService should be used for learning because it's doing a bunch of parsing and UI stuff that most services won't need.

**Comment by glauterpro** [comment]
Yes, I agree, but my point is we should have a complete example, when you say this should be updated, I suppose we will add the service list on the template service component's right? At this moment on template service's we only have method list on the component.
I think this template component should be smart enough to detect if the agent has more than one service/or method and render appropriately.

**Comment by ferrouswheel** [comment]
The dapp doesn't support more than one service. There is an open issue for
this and we should avoid confusing the community with something we might be
removing.
