### ISSUE TITLE
Show number of uses instead of amount of AGI

### ISSUE THREAD

**Issue by w1kke** [singnet/snet-betav1-dapp#226]
In the process flow of creating a payment channel the user is asked to set an amount of AGI for the payment channel. This is misunderstood by a lot of users.
As the price of the service is known this could instead be a slider that let's the user decide on the number of uses instead. This would improve the usability. The corresponding amount of AGI should still be displayed.

**Comment by raamb** [comment]
This is a great idea and we are toying with a similar approach. Essentially one of the UX challenges has been in conveying the idea of paying for a number of calls upfront (this is gas efficient, as the channel is set up with enough funds in one go instead of adding funds multiple times incurring gas cost multiple times). 
The approach we are toying is in terms of selling usage, something like what Metamask displays for gas
![image](https://user-images.githubusercontent.com/43820601/55565356-4d0be400-5717-11e9-8837-41bf3ebd1479.png)

Instead of **Fastest, Fast and Slow** we will have something like 
- Many Calls (fund for 50 calls)
- Few calls (fund for 5 calls)
- Custom (User can choose, we will show current options)
* Ofcourse we will use better terminology and figure the correct set of calls

This ties in with what you are requesting for.

**Comment by w1kke** [comment]
I like the flexible gas pricing, good idea.

Regarding the number of uses - I like sliders for this kind of things, on top you can enter the number of uses:
![image](https://user-images.githubusercontent.com/921146/55605975-4c0a9f00-5777-11e9-8206-58f5dec7356d.png)

I think most people that come to the platform (I saw this in the YouTube streams) at first don't realize what this amount means now. You have the same opinion, which is great. I guess you will also change the description:
The first step in invoking the API is to open a payment channel. The System attempt to resuse any existing channel. If no channels are found a new one will be created. This step involves interactions with MetaMask.

This is a bit cryptic, you talk about interactions with MetaMask but it means that this will trigger a transaction on the Ethereum blockchain. The advantage of opening a payment channel with more uses is not so clear. But you will probably rework this anyhow.

There is also the expiration date for the payment channel, could this become a data + time instead? Like a date + time picker element?

**Comment by w1kke** [comment]
The date thing is already covered in this issue:
https://github.com/singnet/snet-dapp/issues/192
