### ISSUE TITLE
Missing the input parameters after job complete

### ISSUE THREAD

**Issue by glauterpro** [singnet/snet-betav1-dapp#41]
**Describe the bug**
We are missing component state hence the service input parameters after job complete. I don't know if we have a motivation for that, but I think that could have many cases where we need these parameters after job complete. Maybe we need to improve the component's lifecycle.

**To Reproduce**
1. Try to render input parameters on job complete step
4. They are coming undefined

**Expected behavior**
Show the used input parameters on the first step.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: [any OS]
 - Browser [any browser]
 - Version [any version]

**Smartphone (please complete the following information):**
The same desktop information.

**Additional context**
We can have many cases where we need these parameters after job complete.

**Comment by ferrouswheel** [comment]
Most of my UIs require access to the input parameters. Following this issue.

**Comment by ferrouswheel** [comment]
@raamb I'm planning to fix this as all my service UIs require it.

It will involve the `CallComponent` providing a callback to `handleJobInvocation`, this callback will be executed with the grpc response. This is instead of the response being providing it as a property to the CallComponent, since react will replace the component when the passed props change.

**Comment by raamb** [comment]
Hi Joel,
This issue has been resolved. We have changed the lifecycle of the
CallComponent so that it's internal state is not lost across request and
response. Please take the latest code.
All service UIs need to be refactored though. There is a lot of duplicate
code, we will get it this post beta launch.

Thanks,
Raam

**Comment by ferrouswheel** [comment]
I'm managed to reuse the state with the master branch, so this issue can be closed. Not sure but I think #126 is the PR that addresses this.

**Comment by raamb** [comment]
#136 and #170 fix this
